### ISSUE TITLE
运行环境导致的插件无法运行

### ISSUE THREAD

**Issue by KohakUwUwU** [kagg886/maimai-opening-song-game#1]
成功版本：Mirai 2.15 Java HotSpot(TM) 64-Bit Server VM 17.0.8
失败版本：Mirai 2.14 OpenJDK Client VM 11.0.18
[2023-07-24.log](https://github.com/kagg886/maimai-opening-song-game/files/12146868/2023-07-24.log)

**Comment by kagg886** [comment]
为什么要使用jdk11呢(

**Comment by KohakUwUwU** [comment]
> 为什么要使用jdk11呢(

因为不用jdk11的话dice骰娘跑不起来

**Comment by kagg886** [comment]
这样啊，我改一下target

**Comment by kagg886** [comment]
好使了踢我

**Comment by kagg886** [comment]
[试试这个。好了的话，自行close](https://wwub.lanzoue.com/iYMpE13g592h)
