### ISSUE TITLE
好像开字母a不会自动显示A

### ISSUE THREAD

**Issue by xqlmyh** [kagg886/maimai-opening-song-game#2]
好像只有这个字母会这样，我是用自己的SDVX曲库测试的，作者可以检查一下源代码

**Comment by kagg886** [comment]
确实有这个问题，目前尝试修了一下：
effb28fc7dd8e3a6169226a13c7a313cc7ee0822
[请下载这个文件](https://github.com/kagg886/maimai-opening-song-game/issues/2)，确认bug被修复后请自行关闭issue
